local wk = require("which-key")
wk.register({
    f = {
        name = "Files",
        e = { function()
            vim.cmd.Ex()

        end,
            "File Exploer"
        },
    },
}, { prefix = "<leader>" })
local function colemakLayout()
    vim.keymap.set('', "d","g")
    vim.keymap.set('', "e","k")
    vim.keymap.set('', "f","e")
    vim.keymap.set('', "g","t")
    vim.keymap.set('', "i","l")
    vim.keymap.set('', "j","y")
    vim.keymap.set('', "k","n")
    vim.keymap.set('', "l","u")
    vim.keymap.set('', "n","j")
    vim.keymap.set('', "o","p")
    vim.keymap.set('', "p","r")
    vim.keymap.set('', "r","s")
    vim.keymap.set('', "s","d")
    vim.keymap.set('', "t","f")
    vim.keymap.set('', "u","i")
    vim.keymap.set('', "y","o")
    vim.keymap.set('', "D","G")
    vim.keymap.set('', "E","K")
    vim.keymap.set('', "F","E")
    vim.keymap.set('', "G","T")
    vim.keymap.set('', "I","L")
    vim.keymap.set('', "J","Y")
    vim.keymap.set('', "K","N")
    vim.keymap.set('', "L","U")
    vim.keymap.set('', "N","J")
    vim.keymap.set('', "O","P")
    vim.keymap.set('', "P","R")
    vim.keymap.set('', "R","S")
    vim.keymap.set('', "S","D")
    vim.keymap.set('', "T","F")
    vim.keymap.set('', "U","I")
    vim.keymap.set('', "Y","O")
    vim.keymap.set('v', "N", ":m '>+1<CR>gv=gv")
    vim.keymap.set('v', "E", ":m '<-2<CR>gv=gv")
    vim.keymap.set('n', "k", "nzzzv")
    vim.keymap.set('n', "k", "Nzzzv")
end
colemakLayout()
--  vim.keymap.set('v', "N", ":m '>+1<CR>gv=gv")
--  vim.keymap.set('v', "E", ":m '<-2<CR>gv=gv")
--  vim.keymap.set('n', "k", "nzzzv")
--  vim.keymap.set('n', "k", "Nzzzv")
vim.keymap.set('n', "<leader>fs", ":w<CR>")
vim.keymap.set('n', "<C-d>", "<C-d>zz")
vim.keymap.set('n', "<C-u>", "<C-u>zz")

vim.keymap.set("x", "<leader>p", "\"_dP")
vim.keymap.set("n", "Q", "<nop>")
